language: ruby

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker build -t u6kapps/docker-pg_rman .
  - docker run --rm u6kapps/docker-pg_rman --version || true

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker tag u6kapps/docker-pg_rman u6kapps/docker-pg_rman:$TRAVIS_TAG;
      docker push u6kapps/docker-pg_rman;
    else
      echo skip docker push;
    fi
